DROP TABLE IF EXISTS "order";

DROP SEQUENCE IF EXISTS seq1;

CREATE SEQUENCE seq1 START WITH 1;

CREATE TABLE "order" (
    id BIGINT NOT NULL PRIMARY KEY DEFAULT nextval('seq1'),
    orderNumber VARCHAR(255) NOT NULL
);
