DROP TABLE IF EXISTS orderRow;

DROP TABLE IF EXISTS "order";

DROP SEQUENCE IF EXISTS seq2;

CREATE SEQUENCE seq2 START WITH 1;

DROP SEQUENCE IF EXISTS seq1;

CREATE SEQUENCE seq1 START WITH 1;

CREATE TABLE "order" (
    id BIGINT NOT NULL PRIMARY KEY DEFAULT nextval('seq1'),
    orderNumber VARCHAR(255) NOT NULL
);

CREATE TABLE orderRow (
    id BIGINT NOT NULL PRIMARY KEY DEFAULT nextval('seq2'),
    order_id BIGINT REFERENCES "order",
    itemName VARCHAR(255) NOT NULL,
    quantity INTEGER NOT NULL,
    price DECIMAL NOT NULL
);
